### ISSUE TITLE
too much loggin in c_src

### ISSUE THREAD

**Issue by stuart-thackray** [esl/erlang_ale#11]
Hi, 

  there is too much logging in the c_src, for example in gpio src for time sensitive applications, which use up too much of CPU or IO.

For example I transformed this python code (http://learn.adafruit.com/adafruits-raspberry-pi-lesson-10-stepper-motors/software) into http://www.pasteall.org/50299

  I was struggling to figure out what might be the problem, I removed the erlang logging which made  no difference, I also checked top then found the problem. Knew it wasn't erlang, was getting worried/nervious.

  I am no C expert but will try and remove unneeded logging in my opion.

**Comment by knewter** [comment]
This should be closed now that I've merged #12
